from pygame import SYSTEM_CURSOR_SIZEALL, SYSTEM_CURSOR_WAIT, SYSTEM_CURSOR_HAND, SYSTEM_CURSOR_ARROW, SRCALPHA
from pygame.locals import MOUSEBUTTONDOWN, MOUSEBUTTONUP, MOUSEMOTION, USEREVENT, QUIT

WINDOW_WIDTH = 400
WINDOW_HEIGHT = 650
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

STATUS_QUIT = 10
STATUS_HOME = 11
STATUS_GAME = 12

STATUS_HOVER = 20
STATUS_INITIALIZTION = 21

STATUS_SECONDARY_WINING = 0
STATUS_SECONDARY_FAILURE = 1

COLOR_GRAY = (50, 50, 50)
COLOR_CYAN = (0, 165, 175)
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_ORANGE = (230, 95, 35)
COLOR_FLESH = (245, 235, 205)
COLOR_DARK_FLESH = (235, 220, 175)
COLOR_LIGHT_FLESH = (250, 240, 210)

COLOR_MASK = (0, 0, 0, 200)
COLOR_SHADOW = (50, 50, 50, 150)
COLOR_BACKGROUND = (135, 95, 75)

CONFIGURE_PATH = './Config.json'
CONFIGURE_WORD_PATH = './Words.json'

RESOURCES_FONT_MAIN = './Resources/Fonts/Main.ttf'
RESOURCES_FONT_OTHER = './Resources/Fonts/Other.ttf'

RESOURCES_IMAGE_WINING = './Resources/Images/Wining.png'
RESOURCES_IMAGE_FAILURE = './Resources/Images/Failure.png'
